---
apiVersion: v2
name: intel-gpu-plugin
version: 4.4.4
appVersion: 0.20.0
description: The Intel GPU plugin facilitates offloading the processing of computation intensive workloads to GPU hardware
keywords:
  - kubernetes
  - cluster
  - hardware
  - gpu
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/intel-gpu-plugin
icon: https://avatars0.githubusercontent.com/u/17888862?s=400&v=4
sources:
  - https://github.com/intel/intel-device-plugins-for-kubernetes/blob/master/cmd/gpu_plugin
maintainers:
  - name: raefon
    email: raefon@users.noreply.github.com 
dependencies:
  - name: common
    version: ~0.2.0
    repository: https://raefon.github.io/kdlhost-charts/
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Update common to ~0.2.0
