---
apiVersion: v2
appVersion: "rolling"
version: 0.2.4
name: syncthing
description: A continuous file synchronization program.
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/syncthing"
icon: "https://github.com/syncthing/syncthing/raw/main/assets/logo-128.png"
deprecated: false
dependencies:
  - name: common
    version: ~0.2.0
    repository: https://raefon.github.io/kdlhost-charts/
keywords:
  - sync
  - thing
  - syncronization
sources:
  - https://syncthing.net/
  - https://hub.docker.com/r/syncthing/syncthing
maintainers:
  - name: raefon
    email: raefon@users.noreply.github.com 
annotations:
  artifacthub.io/changes: |
    - Update common to ~0.2.0
  artifacthub.io/images: |
    - ghcr.io/raefon/syncthing:rolling