---
apiVersion: v2
appVersion: "rolling"
version: 0.1.4
name: plex
description: The Media Server.
type: application
home: "https://github.com/kdlhost-charts/charts/plex"
icon: ""
deprecated: false
dependencies:
  - name: common
    version: ~0.1.8
    repository: https://raefon.github.io/kdlhost-charts/
keywords:
  - media
  - plex
sources:
  - https://plex.tv/
maintainers:
  - name: raefon
    email: raefon@users.noreply.github.com 
annotations:
  artifacthub.io/changes: |
    - Update docker container image
  artifacthub.io/images: |
    - ghcr.io/raefon/plex:rolling
