apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  issuerRef:
    name: {{ .Values.ingress.clusterIssuer }}
    kind: ClusterIssuer
  secretName: {{ .Release.Name }}-tls
  dnsNames:
  - {{ .Values.ingress.panel }}
  - {{ .Values.ingress.kuber }}
