apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kuber.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: kuber
  {{- with .Values.kuber.deploymentAnnotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  replicas: {{ .Values.kuber.replicaCount }}
  selector:
    matchLabels:
      app: kuber
  template:
    metadata:
      labels:
        app: kuber
    spec:
      serviceAccountName: {{ include "kubectyl.serviceAccountName" . }}
      initContainers:
      {{- range .Values.kuber.initContainers }}
      - name: {{ .name }}
        image: {{ .image }}
        command: {{ .command | toJson }}
        volumeMounts:
        {{- range .volumeMounts }}
          - name: {{ .name }}
            mountPath: {{ .mountPath }}
        {{- end }}
      {{- end }}
      containers:
      - name: kuber
        image: {{ .Values.kuber.image }}
        imagePullPolicy: {{ .Values.kuber.imagePullPolicy }}
        volumeMounts:
        {{- if .Values.ingress.tls.create }}
          - name: ssl-certs
            mountPath: /etc/kubectyl/certs
            readOnly: true
        {{- end }}
          - name: tmp
            mountPath: "/etc/kubectyl"
        ports:
        - containerPort: 80
          name: web
      volumes:
      {{- if .Values.ingress.tls.create }}
        - name: ssl-certs
          secret:
            secretName: {{ .Release.Name }}-tls
      {{- end }}
        - name: tmp
          emptyDir: {}
        - name: config
          configMap:
            name: kuber-config
            defaultMode: 0755
