apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    {{- if .Values.ingress.clusterIssuer }}
    cert-manager.io/issuer: {{ .Values.ingress.clusterIssuer }}
    {{- end }}
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120s"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: {{ .Values.ingress.class }}
  rules:
  - host: {{ .Values.ingress.panel }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "panel.fullname" . }}
            port:
              number: 443
  - host: {{ .Values.ingress.kuber }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "kuber.fullname" . }}
            port:
              number: 443
  tls:
    - secretName: {{ .Release.Name }}-tls
      hosts:
      - {{ .Values.ingress.panel }}
      - {{ .Values.ingress.kuber }}
