kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
    name: storage-sc
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
    numberOfReplicas: "{{ .Values.storage.numberOfReplicas }}"
    dataLocality: "{{ .Values.storage.dataLocality }}"
    staleReplicaTimeout: "2800"
    fromBackup: ""