apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: media-nfs
spec:
    selector:
        matchLabels:
            type: nfs
            app: media
    storageClassName: nfs-direct
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 100Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: downloads-nfs
spec:
    selector:
        matchLabels:
            type: nfs
            app: downloads
    storageClassName: nfs-direct
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 100Gi
