apiVersion: v1
kind: PersistentVolume
metadata:
    name: downloads-nfs-pv
    labels:
        type: nfs
        app: media
spec:
    storageClassName: nfs-direct
    capacity:
        storage: 100Gi
    accessModes:
        - ReadWriteMany
    nfs:
        path: "/mnt/user/Downloads"
        server: {{ .Values.storage.nasIp }}

---

apiVersion: v1
kind: PersistentVolume
metadata:
    name: media-nfs-pv
    labels:
        type: nfs
        app: media
spec:
    storageClassName: nfs-direct
    capacity:
        storage: 100Gi
    accessModes:
        - ReadWriteMany
    nfs:
        path: "/mnt/user/Media"
        server: {{ .Values.storage.nasIp }}