---
apiVersion: v2
name: crowdsec-cloudflare-bouncer
version: 2.0.0
appVersion: v0.3.0
description: A CrowdSec Bouncer that syncs the decisions made by CrowdSec with CloudFlare's firewall. Manages multi user, multi account, multi zone setup. Supports IP, Country and AS scoped decisions.
keywords:
  - kubernetes
  - cluster
  - crowdsec
  - cloudflare
  - bouncer
sources:
  - https://github.com/intel/intel-device-plugins-for-kubernetes/blob/master/cmd/gpu_plugin
maintainers:
  - name: raefon
    email: raefon@users.noreply.github.com 
dependencies:
  - name: common
    version: ~0.2.0
    repository: https://raefon.github.io/kdlhost-charts/
annotations:
  artifacthub.io/changes: |-
    - kind: Changed
      description: Changed to Deployment from Daemonset, added service for prometheus
