---
apiVersion: v2
appVersion: 1.0.0
description: This chart is used to install storage
maintainers:
    - email: raefon@users.noreply.github.com
      name: raefon
name: storage
type: application
version: 2.0.0
