{{- if and .Values.persistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ .Values.appwatcher.name }}"
  namespace: {{ .Release.Namespace }}
{{- with .Values.appwatcher.annotations  }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    app: {{ template "tenet.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    {{- if .Values.appwatcher.additionalLabels }}
    {{ toYaml .Values.appwatcher.additionalLabels | nindent 4 }}
    {{- end }}
spec:
  accessModes:
    - {{ .Values.appwatcher.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.appwatcher.size | quote }}
  storageClassName: "{{ .Values.appwatcher.storageClass }}"
{{- end }}