{{- if and .Values.config-persistence.enabled (not .Values.config-persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.config-persistence.name | quote }}
  namespace: {{ .Release.Namespace }}
{{- with .Values.config-persistence.annotations  }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    app: {{ .Values.config-persistence.name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - {{ .Values.config-persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.config-persistence.size | quote }}
{{- if .Values.config-persistence.storageClass }}
{{- if (eq "-" .Values.config-persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.config-persistence.storageClass }}"
{{- end }}
{{- end }}
{{- end }}