{{- if and .Values.persistence.enabled }}
{{- range .Values.persistence}}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ .name }}"
  namespace: {{ .Release.Namespace }}
{{- with .annotations  }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    app: {{ template "tenet.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - {{ .accessMode | quote }}
  resources:
    requests:
      storage: {{ .size | quote }}
  storageClassName: "{{ .storageClass }}"
{{- end }}
{{- end }}