{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.rclone.name }}-secret"
  namespace: {{ .Release.Namespace }}
stringData:
  configData: |
    [torbox]
    type = webdav
    # Connects to the decypharr service in the same namespace
    url = http://{{ template "tenet.fullname" . }}-decypharr:8080
    vendor = other
{{- end }}