{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  # Result: tenet-%name%-rclone-pv
  name: "{{ .Release.Namespace }}-rclone-pv"
spec:
  accessModes:
    - {{ .Values.rclone.accessMode | default "ReadWriteMany" | quote }}
  capacity:
    storage: {{ .Values.rclone.size | default "100Ti" | quote }}
  persistentVolumeReclaimPolicy: Delete
  mountOptions:
    - allow_other=true
    - uid=568
    - gid=568
    - vfs-read-ahead=128M
    - path-fuse-binary=/usr/bin/fusermount3
  csi:
    driver: rclone.csi.veloxpack.io
    # volumeHandle should also be unique to avoid internal driver conflicts
    volumeHandle: "{{ .Release.Namespace }}-media-vol"
    volumeAttributes:
      remote: "torbox"
      remotePath: "/"
      vfs-cache-mode: "full"
      vfs-cache-max-size: {{ .Values.rclone.cacheSize | default "50G" | quote }}
      buffer-size: {{ .Values.rclone.bufferSize | default "64M" | quote }}
    nodePublishSecretRef:
      name: "{{ .Values.rclone.name }}-secret"
      namespace: {{ .Release.Namespace }}
{{- end }}