{{- if .Values.persistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ .Values.rclone.name }}" # media-%name%
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - {{ .Values.rclone.accessMode | default "ReadWriteMany" | quote }}
  resources:
    requests:
      storage: {{ .Values.rclone.size | default "100Ti" | quote }}
  storageClassName: "" # Force static binding
  # This MUST match the metadata.name of the PV exactly
  volumeName: "{{ .Release.Namespace }}-rclone-pv"
{{- end }}