{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.rclone.name }}-secret"
  namespace: {{ .Release.Namespace }}
stringData:
  configData: |
    [torbox]
    type = webdav
    # Dynamically builds: http://tenet-decypharr.tenet-%name%.svc.cluster.local:8282/webdav/
    url = http://{{ include "tenet.fullname" . }}-decypharr.{{ .Release.Namespace }}.svc.cluster.local:8282/webdav/
    vendor = other
{{- end }}