---
apiVersion: v2
appVersion: 1.0.0
version: 0.0.1
name: tenet
description: Used to provision tenets
type: application
home: "https://github.com/kdlhost-charts/helm-charts/tree/main/charts/tenet"
deprecated: false
dependencies:
  - name: syncthing
    version: ~0.1.8
    repository: https://raefon.github.io/kdlhost-charts/
keywords:
  - tenet
maintainers:
  - name: raefon
    email: raefon@users.noreply.github.com 
annotations:
  artifacthub.io/changes: |
    - Initial